# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-19 10:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('is_quote_status', models.BooleanField(default=False)),
                ('in_reply_to_status_id', models.IntegerField(default=-1)),
                ('favorite_count', models.IntegerField(default=-1)),
                ('retweet_count', models.IntegerField(default=-1)),
                ('source', models.URLField(max_length=300, null=True)),
                ('in_reply_to_user_id', models.IntegerField(null=True)),
                ('lang', models.CharField(max_length=5, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, null=True)),
                ('screen_name', models.CharField(max_length=30, null=True)),
                ('created_at', models.DateTimeField()),
                ('contributors_enabled', models.BooleanField(default=False)),
                ('verified', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='tweet',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.User'),
        ),
    ]
