# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-20 17:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='in_reply_to_status_id',
            field=models.IntegerField(default=-1, null=True),
        ),
    ]
