# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-26 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0003_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='Occurences',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('occurencesNum', models.IntegerField(default=0)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.User')),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='viewer.Word')),
            ],
        ),
        migrations.AddField(
            model_name='word',
            name='said',
            field=models.ManyToManyField(through='viewer.Occurences', to='viewer.User'),
        ),
    ]
