# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-26 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viewer', '0004_auto_20170226_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='word',
            old_name='said',
            new_name='occurencesNum',
        ),
    ]
